FROM python:3.12-alpine

WORKDIR /research

COPY research /research
RUN sed -i 's|https://dl-cdn.alpinelinux.org/alpine|https://mirrors.aliyun.com/alpine|g' /etc/apk/repositories
RUN apk update
RUN apk add --no-cache curl
RUN apk add --no-cache unzip

RUN unzip driver.zip
RUN unzip chrome.zip

RUN pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/


CMD ["python3", "-m", "group_breakout.http"]