FROM python:3.12-alpine

WORKDIR /research

COPY research /research

RUN apk add --no-cache curl
RUN apk add --no-cache unzip

RUN unzip driver.zip
RUN unzip chrome.zip

RUN pip install -r requirements.txt


CMD ["python3", "-m", "group_breakout.http"]