FROM python:3.12-alpine

WORKDIR /research

COPY ./research /research
RUN sed -i 's|https://dl-cdn.alpinelinux.org/alpine|https://mirrors.aliyun.com/alpine|g' /etc/apk/repositories
RUN apk update
RUN apk add --no-cache curl
RUN apk add --no-cache unzip
RUN pip install -r requirements.txt
# RUN sh driver_download.sh
RUN unzip driver.zip
RUN unzip chrome.zip

CMD [ "python3", "-m", "group_breakout.fetch" ]