FROM python:3.12-slim-bookworm

WORKDIR /research
COPY ./research /research
RUN pip install -r requirements.txt -i https://mirrors.tencent.com/pypi/simple/

CMD [ "python3", "-m", "group_breakout.http" ]