from chinese_calendar import holidays

template = f"""// generated by python3 gen.py
export const holidays = new Map<string, string>([
{',\n'.join([f"\t[\"{d.isoformat()}\", \"{s}\"]" for d,s in holidays.items()])}
]);
"""
with open("./constants.ts", 'w+') as f:
    f.write(template)
    print(template)